### ISSUE TITLE
Give Feedback about the current state of the API

### ISSUE THREAD

**Issue by yncyrydybyl** [fahrgemeinschaft/FredEddisonMetaSearch#1]

**Comment by ryildiz** [comment]
This curl request is not working, we tried this with Yan. Would you please help us with this.
Outcome is added at the bottom:
```
curl --location --request POST 'https://frededdison-metasearch-r2g-api-dev.apps.prod.rd2g.de/api/trip/search' \
--header 'Accept: application/json, text/plain, */*' \
--header 'Referer: http://localhost:8100/' \
--header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 YaBrowser/20.6.1.148 Yowser/2.5 Safari/537.36' \
--header 'Content-Type: application/json' \
--header 'Content-Type: text/plain' \
--header 'Cookie: d5043807cb0028fb9982722db46a12c5=cb84fbc115a57c6f8593bc3a44cb59de; XSRF-TOKEN=eyJpdiI6IlZYNE5XQzV6dzRuZDZQenhPNjlQeVE9PSIsInZhbHVlIjoiYzdXN0VnbmhpdmxkZHc4NVZEQncrQ09uakphbnBoZktqNFBlSnlvVjhQbGtyTHFpNEhyR2Z3L0wzLzZEL3N2ZSIsIm1hYyI6IjM4Y2IxNmQyMWZkMDdiMTIwZmEwOWQyOGMzMWQ0MWQ2NTI4MzJlZDg3OWU3NjNlNWQzYjRmZTg4NTYzNjQyMmIifQ%3D%3D; laravel_session=eyJpdiI6InhFSTRlVHlxbjlkWFlCak1OTjQzbEE9PSIsInZhbHVlIjoiOXRIYmdLZWt5aU5tZjRUS21PbTZad0JjdUVBYTB5ak1iKzV2V0ZPekVMdWFvaHl0blVPVnNyR3YzTmtEcE82aSIsIm1hYyI6IjhjYWExZGZiMmVjZjUyOGUxZTE2YWVlNDk1NjQxYTAxNDVmNTE4NDZjOWRlZmY5ZjNmYWJlMDc3ZWY3MGUxYTUifQ%3D%3D' \
--data-raw '{"startPoint":{"location":{"latitude":52.5198535,"longitude":13.4385964}},"endPoint":{"location":{"latitude":52.5198535,"longitude":13.4385964}},"departure":{"time":"2020-06-20T11:06:04.690Z","toleranceInDays":0},"arrival":null,"page":{"firstIndex":20,"page":0,"pageSize":20},"reoccurDays":null,"availabilityStarts":"2020-06-20T11:06:04.690Z","availabilityEnds":null,"tripTypes":[0],"transportTypes":[0],"animals":2,"baggage":1,"gender":2,"organizations":[],"smoking":3}'

```

Outcome is:
```

{
    "message": "Undefined index: radius",
    "exception": "ErrorException",
    "file": "/opt/app-root/src/app/Http/Controllers/TripController.php",
    "line": 54,
    "trace": [
        {
            "file": "/opt/app-root/src/app/Http/Controllers/TripController.php",
            "line": 54,
            "function": "handleError",
            "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
            "type": "->"
        },
        {
            "function": "search",
            "class": "App\\Http\\Controllers\\TripController",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
            "line": 54,
            "function": "call_user_func_array"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 225,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
            "line": 182,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 685,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",
            "line": 41,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php",
            "line": 59,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 687,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 662,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 628,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 617,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 165,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 128,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
            "line": 63,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/fruitcake/laravel-cors/src/HandleCors.php",
            "line": 36,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fruitcake\\Cors\\HandleCors",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/fideloper/proxy/src/TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 167,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 103,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 140,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 109,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/opt/app-root/src/public/index.php",
            "line": 55,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        }
    ]
}

```

**Comment by mlipke** [comment]
`startPoint` and `endPoint` in your request are missing a `radius`. We've added default values for those so requests without them shouldn't fail anymore. 

This should also work:
```
'{"startPoint":{"location":{"latitude":52.5198535,"longitude":13.4385964}, "radius": "50.0"},"endPoint":{"location":{"latitude":52.5198535,"longitude":13.4385964}, "radius": "50.0"},"departure":{"time":"2020-06-24T11:06:04.690Z","toleranceInDays":0},"arrival":null,"page":{"firstIndex":20,"page":0,"pageSize":20},"reoccurDays":null,"availabilityStarts":"2020-06-23T11:06:04.690Z","availabilityEnds":null,"tripTypes":[0],"transportTypes":[0],"animals":2,"baggage":1,"gender":2,"organizations":[],"smoking":3}'
```

**Comment by yncyrydybyl** [comment]
That works now. 
Why isn't it returning Results from mifaz for berlin -> Hamburg

```
curl --location --request POST 'https://frededdison-metasearch-r2g-api-dev.apps.prod.rd2g.de/api/trip/search' \
--header 'Accept: application/json, text/plain, */*' \
--header 'Referer: http://localhost:8100/' \
--header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 YaBrowser/20.6.1.148 Yowser/2.5 Safari/537.36' \
--header 'Content-Type: application/json' \
--header 'Content-Type: text/plain' \
--header 'Cookie: d5043807cb0028fb9982722db46a12c5=cb84fbc115a57c6f8593bc3a44cb59de; XSRF-TOKEN=eyJpdiI6IlZYNE5XQzV6dzRuZDZQenhPNjlQeVE9PSIsInZhbHVlIjoiYzdXN0VnbmhpdmxkZHc4NVZEQncrQ09uakphbnBoZktqNFBlSnlvVjhQbGtyTHFpNEhyR2Z3L0wzLzZEL3N2ZSIsIm1hYyI6IjM4Y2IxNmQyMWZkMDdiMTIwZmEwOWQyOGMzMWQ0MWQ2NTI4MzJlZDg3OWU3NjNlNWQzYjRmZTg4NTYzNjQyMmIifQ%3D%3D; laravel_session=eyJpdiI6InhFSTRlVHlxbjlkWFlCak1OTjQzbEE9PSIsInZhbHVlIjoiOXRIYmdLZWt5aU5tZjRUS21PbTZad0JjdUVBYTB5ak1iKzV2V0ZPekVMdWFvaHl0blVPVnNyR3YzTmtEcE82aSIsIm1hYyI6IjhjYWExZGZiMmVjZjUyOGUxZTE2YWVlNDk1NjQxYTAxNDVmNTE4NDZjOWRlZmY5ZjNmYWJlMDc3ZWY3MGUxYTUifQ%3D%3D' \
--data-raw '{"startPoint":{"location":{"latitude":52.5198535,"longitude":13.4385964}},"endPoint":{"location":{"latitude":53.5437641,"longitude":10.0099133}},"departure":{"time":"2020-06-25T11:06:04.690Z","toleranceInDays":1},"arrival":null,"page":{"firstIndex":20,"page":0,"pageSize":20},"reoccurDays":null,"availabilityStarts":"2020-06-23T11:06:04.690Z","availabilityEnds":null,"tripTypes":[0],"transportTypes":[0],"animals":2,"baggage":1,"gender":2,"organizations":[],"smoking":3}'
```

```
"message": "Trying to get property 'toleranceInDays' of non-object",
    "exception": "ErrorException",
    "file": "/opt/app-root/src/app/Search.php",
    "line": 64,
    "trace": 
```
Can you provide a working request for results from mifaz?

**Comment by mlipke** [comment]
bad17ea977ee19877006f0b44d0dc604cc17de3a should have fixed that issue, is the latest version deployed?

**Comment by merlinro** [comment]
We fixed it. 
https://frededdison-metasearch-r2g-api-dev.apps.prod.rd2g.de/api/trip/search

**Comment by yncyrydybyl** [comment]
@merlinro We added the key to the environment. But still not results.

**Comment by merlinro** [comment]
I think this is all clear
